server:
  port: 8081


spring:
  datasource:
     url: jdbc:mysql://localhost:3306/pobox1?autoReconnect=true&useSSL=false&useUnicode=true&serverTimezone=UTC
     username: root
     password: root
     driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
     init:
       continue-on-error: false
